### ISSUE TITLE
CALabel crash because of font

### ISSUE THREAD

**Issue by lazycat1711** [9miao/CrossApp#101]
win32 project crash because CALabel doesnt have font

![image](https://cloud.githubusercontent.com/assets/10325710/9295896/0173d19a-44a8-11e5-87dc-19595166104c.png)

**Comment by zhujnt** [comment]
You must call this function（CAImage::getFontHeight） in the main thread.

**Comment by lazycat1711** [comment]
its happend in hello world project. i just create and run project then it crash.

**Comment by lazycat1711** [comment]
another problem is simhei.ttf is missing in window 10 lang English  but its set default in 
CrossApp\platform\CAFreeTypeFont.cpp line 1049 strcat(sTTFont,"\\fonts\\simhei.ttf");
