### ISSUE TITLE
主干代码 hellocpp VS2013编译出错，另：编出的DEBUG版本程序，直接运行出错

### ISSUE THREAD

**Issue by huangyt** [9miao/CrossApp#32]
你好：官方说支持WIN32平台，为什么不能直接运行呢？调试状态倒是可以。点击直接提示：HelloCpp.exe已停止工作。

**Comment by crossapp** [comment]
不能正常运行，应该是资源文件和程序不在一个目录下，找不到资源文件的缘故。

**Comment by huangyt** [comment]
谢谢，我没怎么看代码，把病源文件拷过来后正常了

**Comment by KevinLion** [comment]
恩，一些项目配置需要注意一下
