### ISSUE TITLE
Assert failed: Could not attach Image to framebuffer

### ISSUE THREAD

**Issue by Juude** [9miao/CrossApp#49]
当添加一个Controller时候，偶尔出现
`Assert failed: Could not attach Image to framebuffer`错误

**Comment by detours** [comment]
请问您是哪个版本？什么系统环境？

**Comment by Juude** [comment]
版本1.00 在linux下开发的

**Comment by detours** [comment]
CrossApp暂时还没有支持linux

**Comment by Juude** [comment]
@detours 后来发现如果不是在ui线程里操作才会有这个问题
请问CrossApp有没有消息队列　可以传递个消息给主线程操作

**Comment by 9miao** [comment]
可以用CASchedule 切换到UI线程

**Comment by Juude** [comment]
谢谢! @9miao
