### ISSUE TITLE
ios开启-ObjC，真机上编译报错

### ISSUE THREAD

**Issue by tanjie0037** [9miao/CrossApp#78]
ios开启了linker flag -ObjC，真机（iphone4, iphone5s等）上编译报错：
Undefined symbols for architecture armv7:
  "_SDL_main", referenced from:
      -[SDLUIKitDelegate postFinishLaunch] in libCrossApp.a(SDL_uikitappdelegate.o)
ld: symbol(s) not found for architecture armv7
clang: error: linker command failed with exit code 1 (use -v to see invocation)

![image](https://cloud.githubusercontent.com/assets/7553325/7981805/06efee4a-0ae4-11e5-9d42-871a736a866e.png)

**Comment by tanjie0037** [comment]
i fix it using -all_load&-ObjC instaed

**Comment by 9miao** [comment]
请问你为什么要开启-Objc

**Comment by tanjie0037** [comment]
接入了ios第三方sdk，必须开启这个

**Comment by netbaby** [comment]
如果没有用到SDL，libCrossApp工程移除libSDL2.a引用
